import type { CardDef, CardInstance } from '../types';
import { applyPlusPlus } from './plusplus';

export const BLOOD_MAGE_CARD_DEFS: Record<string, CardDef> = {
  // ── Starter ──
  v_blood_strike: {
    id: 'v_blood_strike',
    name: '피의 일격',
    type: 'attack',
    rarity: 'starter',
    cost: 1,
    target: 'enemy',
    description: 'HP -2. 9 데미지.',
    effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 9 }],
  },
  v_crimson_guard: {
    id: 'v_crimson_guard',
    name: '핏빛 방패',
    type: 'skill',
    rarity: 'starter',
    cost: 1,
    target: 'self',
    description: '방어도 +5.',
    effects: [{ kind: 'block', amount: 5 }],
  },
  v_drain: {
    id: 'v_drain',
    name: '흡혈',
    type: 'attack',
    rarity: 'starter',
    cost: 1,
    target: 'enemy',
    description: '5 흡혈 데미지.',
    effects: [{ kind: 'lifesteal', amount: 5 }],
  },

  // ── Common ──
  v_hemorrhage: {
    id: 'v_hemorrhage',
    name: '출혈',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '4 데미지를 두 번.',
    effects: [{ kind: 'damage', amount: 4, times: 2 }],
  },
  v_blood_offering: {
    id: 'v_blood_offering',
    name: '피의 제물',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: 'HP -3. 2장 드로우.',
    effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'draw', amount: 2 }],
  },
  v_transfusion: {
    id: 'v_transfusion',
    name: '수혈',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '8 흡혈 데미지.',
    effects: [{ kind: 'lifesteal', amount: 8 }],
  },
  v_sanguine_armor: {
    id: 'v_sanguine_armor',
    name: '핏빛 갑옷',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: 'HP -3. 방어도 +12.',
    effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'block', amount: 12 }],
  },
  v_coagulate: {
    id: 'v_coagulate',
    name: '응고',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '방어도 +6. 재생 +2.',
    effects: [{ kind: 'block', amount: 6 }, { kind: 'apply_self', status: 'regen', amount: 2 }],
  },
  v_bloodletting: {
    id: 'v_bloodletting',
    name: '사혈',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: 'HP -4. 에너지 +2.',
    effects: [{ kind: 'lose_hp', amount: 4 }, { kind: 'energy', amount: 2 }],
  },
  v_crimson_slash: {
    id: 'v_crimson_slash',
    name: '선혈의 참격',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '8 데미지. 3 회복.',
    effects: [{ kind: 'damage', amount: 8 }, { kind: 'heal', amount: 3 }],
  },
  v_blood_pact: {
    id: 'v_blood_pact',
    name: '혈의 서약',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  v_leech: {
    id: 'v_leech',
    name: '흡수',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '6 흡혈 데미지. 약화 +1.',
    effects: [{ kind: 'lifesteal', amount: 6 }, { kind: 'apply_enemy', status: 'weak', amount: 1 }],
  },
  v_gore: {
    id: 'v_gore',
    name: '파혈',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: 'HP -2. 12 데미지.',
    effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 12 }],
  },
  v_vital_drain: {
    id: 'v_vital_drain',
    name: '생기 흡수',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '6 회복.',
    effects: [{ kind: 'heal', amount: 6 }],
  },
  v_blood_rush: {
    id: 'v_blood_rush',
    name: '피의 쇄도',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: 'HP -2. 7 데미지. 1장 드로우.',
    effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 7 }, { kind: 'draw', amount: 1 }],
  },

  // ── Uncommon ──
  v_sanguine_fury: {
    id: 'v_sanguine_fury',
    name: '핏빛 분노',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'enemy',
    description: 'HP -3. 8 데미지를 두 번.',
    effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage', amount: 8, times: 2 }],
  },
  v_blood_shield: {
    id: 'v_blood_shield',
    name: '피의 방벽',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: 'HP를 잃는 카드 사용 시 잃은 HP만큼 방어도 획득.',
    effects: [{ kind: 'apply_self', status: 'blood_armor', amount: 1 }],
  },
  v_exsanguinate: {
    id: 'v_exsanguinate',
    name: '방혈',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'enemy',
    description: 'HP -5. 18 흡혈 데미지.',
    effects: [{ kind: 'lose_hp', amount: 5 }, { kind: 'lifesteal', amount: 18 }],
  },
  v_crimson_wave: {
    id: 'v_crimson_wave',
    name: '핏빛 파동',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'all_enemies',
    description: 'HP -3. 모든 적에게 10 데미지.',
    effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage_all', amount: 10 }],
  },
  v_hemophilia: {
    id: 'v_hemophilia',
    name: '혈우',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '취약 +2. 약화 +1.',
    effects: [
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
      { kind: 'apply_enemy', status: 'weak', amount: 1 },
    ],
  },
  v_blood_feast: {
    id: 'v_blood_feast',
    name: '피의 향연',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'enemy',
    description: '7 흡혈 데미지를 두 번.',
    effects: [{ kind: 'lifesteal', amount: 7, times: 2 }],
  },
  v_iron_will: {
    id: 'v_iron_will',
    name: '철의 의지',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: 'HP -2. 방어도 +8. 힘 +1.',
    effects: [
      { kind: 'lose_hp', amount: 2 },
      { kind: 'block', amount: 8 },
      { kind: 'apply_self', status: 'strength', amount: 1 },
    ],
  },
  v_siphon_life: {
    id: 'v_siphon_life',
    name: '생명력 착취',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '5 흡혈 데미지. 재생 +3.',
    effects: [{ kind: 'lifesteal', amount: 5 }, { kind: 'apply_self', status: 'regen', amount: 3 }],
  },
  v_blood_rage: {
    id: 'v_blood_rage',
    name: '피의 광기',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: 'HP를 잃는 카드 사용 시 힘 +1.',
    effects: [{ kind: 'apply_self', status: 'blood_power', amount: 1 }],
  },
  v_red_tide: {
    id: 'v_red_tide',
    name: '핏빛 조류',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '7 흡혈 데미지. 1장 드로우.',
    effects: [{ kind: 'lifesteal', amount: 7 }, { kind: 'draw', amount: 1 }],
  },
  v_marrow_tap: {
    id: 'v_marrow_tap',
    name: '골수 추출',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    target: 'self',
    description: 'HP -5. 3장 드로우.',
    effects: [{ kind: 'lose_hp', amount: 5 }, { kind: 'draw', amount: 3 }],
  },
  v_clot: {
    id: 'v_clot',
    name: '혈전',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '방어도 +10. 금속화 +2.',
    effects: [{ kind: 'block', amount: 10 }, { kind: 'apply_self', status: 'metallicize', amount: 2 }],
  },
  v_scarlet_dance: {
    id: 'v_scarlet_dance',
    name: '선홍의 춤',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: 'HP -2. 5 데미지를 세 번.',
    effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 5, times: 3 }],
  },
  v_essence_drain: {
    id: 'v_essence_drain',
    name: '정수 흡수',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 8 흡혈 데미지.',
    effects: [{ kind: 'lifesteal_all', amount: 8 }],
  },

  // ── Rare ──
  v_blood_nova: {
    id: 'v_blood_nova',
    name: '피의 폭발',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'all_enemies',
    description: 'HP -8. 모든 적에게 30 데미지.',
    effects: [{ kind: 'lose_hp', amount: 8 }, { kind: 'damage_all', amount: 30 }],
  },
  v_immortal_coil: {
    id: 'v_immortal_coil',
    name: '불멸의 코일',
    type: 'power',
    rarity: 'rare',
    cost: 2,
    target: 'self',
    description: '재생 +5.',
    effects: [{ kind: 'apply_self', status: 'regen', amount: 5 }],
  },
  v_crimson_pact: {
    id: 'v_crimson_pact',
    name: '핏빛 계약',
    type: 'power',
    rarity: 'rare',
    cost: 2,
    target: 'self',
    description: '의식 +2. 재생 +2. 선천.',
    effects: [
      { kind: 'apply_self', status: 'ritual', amount: 2 },
      { kind: 'apply_self', status: 'regen', amount: 2 },
    ],
    innate: true,
  },
  v_exorcism: {
    id: 'v_exorcism',
    name: '피의 정화',
    type: 'attack',
    rarity: 'rare',
    cost: 1,
    target: 'enemy',
    description: 'HP -6. 20 데미지. 취약 +2.',
    effects: [
      { kind: 'lose_hp', amount: 6 },
      { kind: 'damage', amount: 20 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
  },
  v_transfuse: {
    id: 'v_transfuse',
    name: '전혈 수혈',
    type: 'skill',
    rarity: 'rare',
    cost: 1,
    target: 'self',
    description: '15 회복. 소멸.',
    effects: [{ kind: 'heal', amount: 15 }],
    exhaust: true,
  },
  v_hemomancer: {
    id: 'v_hemomancer',
    name: '혈법',
    type: 'power',
    rarity: 'rare',
    cost: 1,
    target: 'self',
    description: 'HP를 잃는 카드 사용 시 방어도 +N, 힘 +1.',
    effects: [
      { kind: 'apply_self', status: 'blood_armor', amount: 1 },
      { kind: 'apply_self', status: 'blood_power', amount: 1 },
    ],
  },
  v_last_drop: {
    id: 'v_last_drop',
    name: '마지막 한 방울',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: 'HP -4. 24 데미지. 힘 +2. 소멸.',
    effects: [
      { kind: 'lose_hp', amount: 4 },
      { kind: 'damage', amount: 24 },
      { kind: 'apply_self', status: 'strength', amount: 2 },
    ],
    exhaust: true,
  },
};

const BLOOD_MAGE_UPGRADE_MAP: Record<string, Partial<CardDef>> = {
  v_blood_strike:    { name: '피의 일격+',     description: 'HP -2. 12 데미지.',                effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 12 }] },
  v_crimson_guard:   { name: '핏빛 방패+',     description: '방어도 +8.',                       effects: [{ kind: 'block', amount: 8 }] },
  v_drain:           { name: '흡혈+',          description: '7 흡혈 데미지.',                    effects: [{ kind: 'lifesteal', amount: 7 }] },
  v_hemorrhage:      { name: '출혈+',          description: '5 데미지를 두 번.',                 effects: [{ kind: 'damage', amount: 5, times: 2 }] },
  v_blood_offering:  { name: '피의 제물+',     description: 'HP -2. 2장 드로우.',                effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'draw', amount: 2 }] },
  v_transfusion:     { name: '수혈+',          description: '11 흡혈 데미지.',                   effects: [{ kind: 'lifesteal', amount: 11 }] },
  v_sanguine_armor:  { name: '핏빛 갑옷+',     description: 'HP -3. 방어도 +16.',                effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'block', amount: 16 }] },
  v_coagulate:       { name: '응고+',          description: '방어도 +8. 재생 +3.',               effects: [{ kind: 'block', amount: 8 }, { kind: 'apply_self', status: 'regen', amount: 3 }] },
  v_bloodletting:    { name: '사혈+',          description: 'HP -3. 에너지 +2.',                 effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'energy', amount: 2 }] },
  v_crimson_slash:   { name: '선혈의 참격+',   description: '11 데미지. 4 회복.',                 effects: [{ kind: 'damage', amount: 11 }, { kind: 'heal', amount: 4 }] },
  v_blood_pact:      { name: '혈의 서약+',     description: '힘 +3.',                            effects: [{ kind: 'apply_self', status: 'strength', amount: 3 }] },
  v_leech:           { name: '흡수+',          description: '8 흡혈 데미지. 약화 +2.',            effects: [{ kind: 'lifesteal', amount: 8 }, { kind: 'apply_enemy', status: 'weak', amount: 2 }] },
  v_gore:            { name: '파혈+',          description: 'HP -2. 16 데미지.',                 effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 16 }] },
  v_vital_drain:     { name: '생기 흡수+',     description: '9 회복.',                            effects: [{ kind: 'heal', amount: 9 }] },
  v_blood_rush:      { name: '피의 쇄도+',     description: 'HP -2. 10 데미지. 1장 드로우.',      effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 10 }, { kind: 'draw', amount: 1 }] },
  v_sanguine_fury:   { name: '핏빛 분노+',     description: 'HP -3. 10 데미지를 두 번.',          effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage', amount: 10, times: 2 }] },
  v_blood_shield:    { name: '피의 방벽+',     description: 'HP를 잃는 카드 사용 시 잃은 HP의 2배 방어도 획득.', effects: [{ kind: 'apply_self', status: 'blood_armor', amount: 2 }] },
  v_exsanguinate:    { name: '방혈+',          description: 'HP -4. 22 흡혈 데미지.',             effects: [{ kind: 'lose_hp', amount: 4 }, { kind: 'lifesteal', amount: 22 }] },
  v_crimson_wave:    { name: '핏빛 파동+',     description: 'HP -3. 모든 적에게 14 데미지.',       effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage_all', amount: 14 }] },
  v_hemophilia:      { name: '혈우+',          description: '취약 +3. 약화 +2.',                 effects: [{ kind: 'apply_enemy', status: 'vulnerable', amount: 3 }, { kind: 'apply_enemy', status: 'weak', amount: 2 }] },
  v_blood_feast:     { name: '피의 향연+',     description: '9 흡혈 데미지를 두 번.',              effects: [{ kind: 'lifesteal', amount: 9, times: 2 }] },
  v_iron_will:       { name: '철의 의지+',     description: 'HP -2. 방어도 +11. 힘 +2.',          effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'block', amount: 11 }, { kind: 'apply_self', status: 'strength', amount: 2 }] },
  v_siphon_life:     { name: '생명력 착취+',   description: '7 흡혈 데미지. 재생 +4.',             effects: [{ kind: 'lifesteal', amount: 7 }, { kind: 'apply_self', status: 'regen', amount: 4 }] },
  v_blood_rage:      { name: '피의 광기+',     description: 'HP를 잃는 카드 사용 시 힘 +2.',       effects: [{ kind: 'apply_self', status: 'blood_power', amount: 2 }] },
  v_red_tide:        { name: '핏빛 조류+',     description: '10 흡혈 데미지. 1장 드로우.',          effects: [{ kind: 'lifesteal', amount: 10 }, { kind: 'draw', amount: 1 }] },
  v_marrow_tap:      { name: '골수 추출+',     description: 'HP -4. 3장 드로우.',                  effects: [{ kind: 'lose_hp', amount: 4 }, { kind: 'draw', amount: 3 }] },
  v_clot:            { name: '혈전+',          description: '방어도 +13. 금속화 +3.',              effects: [{ kind: 'block', amount: 13 }, { kind: 'apply_self', status: 'metallicize', amount: 3 }] },
  v_scarlet_dance:   { name: '선홍의 춤+',     description: 'HP -2. 6 데미지를 세 번.',            effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'damage', amount: 6, times: 3 }] },
  v_essence_drain:   { name: '정수 흡수+',     description: '모든 적에게 11 흡혈 데미지.',          effects: [{ kind: 'lifesteal_all', amount: 11 }] },
  v_blood_nova:      { name: '피의 폭발+',     description: 'HP -6. 모든 적에게 38 데미지.',       effects: [{ kind: 'lose_hp', amount: 6 }, { kind: 'damage_all', amount: 38 }] },
  v_immortal_coil:   { name: '불멸의 코일+',   description: '재생 +7.',                            effects: [{ kind: 'apply_self', status: 'regen', amount: 7 }] },
  v_crimson_pact:    { name: '핏빛 계약+',     description: '의식 +3. 재생 +3. 선천.',             effects: [{ kind: 'apply_self', status: 'ritual', amount: 3 }, { kind: 'apply_self', status: 'regen', amount: 3 }] },
  v_exorcism:        { name: '피의 정화+',     description: 'HP -5. 26 데미지. 취약 +3.',          effects: [{ kind: 'lose_hp', amount: 5 }, { kind: 'damage', amount: 26 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  v_transfuse:       { name: '전혈 수혈+',     description: '20 회복. 소멸.',                      effects: [{ kind: 'heal', amount: 20 }] },
  v_hemomancer:      { name: '혈법+',          description: 'HP를 잃는 카드 사용 시 방어도 +2N, 힘 +2.', effects: [{ kind: 'apply_self', status: 'blood_armor', amount: 2 }, { kind: 'apply_self', status: 'blood_power', amount: 2 }] },
  v_last_drop:       { name: '마지막 한 방울+', description: 'HP -3. 32 데미지. 힘 +3. 소멸.',     effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage', amount: 32 }, { kind: 'apply_self', status: 'strength', amount: 3 }] },
};

export function bloodMageGetEffectiveDef(card: CardInstance): CardDef {
  const base = BLOOD_MAGE_CARD_DEFS[card.defId];
  if (!base) return { id: card.defId, name: '???', type: 'skill', rarity: 'common', cost: 0, target: 'none', description: '삭제된 카드', effects: [] };
  if (!card.upgraded) return base;
  const up = BLOOD_MAGE_UPGRADE_MAP[card.defId];
  const plusDef = up ? { ...base, ...up } : base;
  if ((card.upgraded ?? 0) >= 2) return applyPlusPlus(plusDef);
  return plusDef;
}

export function canUpgradeBloodMage(card: CardInstance): boolean {
  return (card.upgraded ?? 0) < 2 && card.defId in BLOOD_MAGE_UPGRADE_MAP;
}

const BLOOD_MAGE_CARD_LIST = Object.values(BLOOD_MAGE_CARD_DEFS);
export const BLOOD_MAGE_COMMON_CARDS   = BLOOD_MAGE_CARD_LIST.filter((c) => c.rarity === 'common');
export const BLOOD_MAGE_UNCOMMON_CARDS = BLOOD_MAGE_CARD_LIST.filter((c) => c.rarity === 'uncommon');
export const BLOOD_MAGE_RARE_CARDS     = BLOOD_MAGE_CARD_LIST.filter((c) => c.rarity === 'rare');
