import type { CardDef, CardInstance } from '../types';

export const ENGINEER_CARD_DEFS: Record<string, CardDef> = {
  // ── Starter ──
  n_wrench: {
    id: 'n_wrench',
    name: '렌치 타격',
    type: 'attack',
    rarity: 'starter',
    cost: 1,
    target: 'enemy',
    description: '6 데미지.',
    effects: [{ kind: 'damage', amount: 6 }],
  },
  n_shield_gen: {
    id: 'n_shield_gen',
    name: '에너지 실드',
    type: 'skill',
    rarity: 'starter',
    cost: 1,
    target: 'self',
    description: '방어도 +5.',
    effects: [{ kind: 'block', amount: 5 }],
  },

  // ── Common ──
  n_light_drone: {
    id: 'n_light_drone',
    name: '경량 드론',
    type: 'power',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '드론 배치: 매턴 랜덤 적에게 6 데미지.',
    effects: [{ kind: 'apply_self', status: 'drone_basic', amount: 6 }],
  },
  n_shrapnel: {
    id: 'n_shrapnel',
    name: '파편 투사',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 8 데미지.',
    effects: [{ kind: 'damage_all', amount: 8 }],
  },
  n_rivet: {
    id: 'n_rivet',
    name: '리벳건',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '5 데미지를 두 번.',
    effects: [{ kind: 'damage', amount: 5, times: 2 }],
  },
  n_overclock: {
    id: 'n_overclock',
    name: '오버클럭',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  n_repair: {
    id: 'n_repair',
    name: '수리 도구',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '방어도 +8. 1장 드로우.',
    effects: [
      { kind: 'block', amount: 8 },
      { kind: 'draw', amount: 1 },
    ],
  },
  n_mag_field: {
    id: 'n_mag_field',
    name: '자기장 방벽',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '방어도 +7. 무작위 카드 1장 소멸.',
    effects: [
      { kind: 'block', amount: 7 },
      { kind: 'exhaust_random_hand' },
    ],
  },
  n_emp: {
    id: 'n_emp',
    name: '전자기 충격',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'enemy',
    description: '11 데미지. 빙결 +1.',
    effects: [
      { kind: 'damage', amount: 11 },
      { kind: 'apply_enemy', status: 'freeze', amount: 1 },
    ],
  },
  n_spark: {
    id: 'n_spark',
    name: '스파크',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '7 데미지. 1장 드로우.',
    effects: [
      { kind: 'damage', amount: 7 },
      { kind: 'draw', amount: 1 },
    ],
  },
  n_plating: {
    id: 'n_plating',
    name: '장갑 도금',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '5 데미지. 방어도 +5.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'block', amount: 5 },
    ],
  },
  n_beam: {
    id: 'n_beam',
    name: '집속 빔',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 4 데미지. 취약 +1.',
    effects: [
      { kind: 'damage_all', amount: 4 },
      { kind: 'apply_all', status: 'vulnerable', amount: 1 },
    ],
  },

  // ── Uncommon ──
  n_heavy_drone: {
    id: 'n_heavy_drone',
    name: '중형 드론',
    type: 'power',
    rarity: 'uncommon',
    cost: 2,
    target: 'self',
    description: '드론 배치: 2턴마다 랜덤 적에게 12 데미지.',
    effects: [{ kind: 'apply_self', status: 'drone_heavy', amount: 12 }],
  },
  n_frost_drone: {
    id: 'n_frost_drone',
    name: '냉각 드론',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '드론 배치: 2턴마다 랜덤 적에게 빙결 +1.',
    effects: [{ kind: 'apply_self', status: 'drone_ice', amount: 1 }],
  },
  n_flame_drone: {
    id: 'n_flame_drone',
    name: '화염 드론',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '드론 배치: 매턴 랜덤 적에게 화상 +3.',
    effects: [{ kind: 'apply_self', status: 'drone_burn', amount: 3 }],
  },
  n_eject: {
    id: 'n_eject',
    name: '긴급 탈출',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    target: 'self',
    description: 'HP -3. 에너지 +2.',
    effects: [
      { kind: 'lose_hp', amount: 3 },
      { kind: 'energy', amount: 2 },
    ],
  },
  n_barrier: {
    id: 'n_barrier',
    name: '방벽 생성기',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '방어도 +10. (이번 턴 한정)',
    effects: [{ kind: 'block', amount: 10 }],
    ethereal: true,
  },
  n_acid: {
    id: 'n_acid',
    name: '산성탄',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '5 데미지. 중독 +5.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'apply_enemy', status: 'poison', amount: 5 },
    ],
  },
  n_auto_repair: {
    id: 'n_auto_repair',
    name: '자동 수리',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    target: 'self',
    description: '재생 +5.',
    effects: [{ kind: 'apply_self', status: 'regen', amount: 5 }],
  },
  n_reinforce: {
    id: 'n_reinforce',
    name: '강화 코팅',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '턴 종료 시 방어도 +3.',
    effects: [{ kind: 'apply_self', status: 'metallicize', amount: 3 }],
  },
  n_power_surge: {
    id: 'n_power_surge',
    name: '동력 증폭',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  n_chain_bomb: {
    id: 'n_chain_bomb',
    name: '연쇄 폭탄',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '8 데미지. 사용할 때마다 영구 데미지 +2.',
    effects: [{ kind: 'damage', amount: 8 }],
    scaling: { kind: 'on_play', amount: 2 },
  },

  // ── Rare ──
  n_siege_drone: {
    id: 'n_siege_drone',
    name: '공성 드론',
    type: 'power',
    rarity: 'rare',
    cost: 2,
    target: 'self',
    description: '드론 배치: 3턴마다 모든 적에게 10 데미지.',
    effects: [{ kind: 'apply_self', status: 'drone_aoe', amount: 10 }],
  },
  n_tesla: {
    id: 'n_tesla',
    name: '테슬라 코일',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'enemy',
    description: '32 데미지. 취약 +2.',
    effects: [
      { kind: 'damage', amount: 32 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
  },
  n_meltdown: {
    id: 'n_meltdown',
    name: '노심 용해',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: 'HP -5. 18 데미지.',
    effects: [
      { kind: 'lose_hp', amount: 5 },
      { kind: 'damage', amount: 18 },
    ],
    exhaust: true,
  },
  n_perpetual: {
    id: 'n_perpetual',
    name: '영구 기관',
    type: 'power',
    rarity: 'rare',
    cost: 2,
    target: 'self',
    description: '턴 시작 시 힘 +2. 선천.',
    effects: [{ kind: 'apply_self', status: 'ritual', amount: 2 }],
    innate: true,
  },

  // ── 공학자 콤보 시너지 ─────────────────────────────────────
  n_precise: {
    id: 'n_precise',
    name: '정밀 타격',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '8 데미지. 이번 턴 첫 카드면 +8 데미지.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'conditional', condition: { kind: 'first_this_turn' }, then: [{ kind: 'damage', amount: 8 }] },
    ],
  },
  n_chain_reaction: {
    id: 'n_chain_reaction',
    name: '연쇄 반응',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '7 데미지. 직전이 효과카드면 +6 데미지.',
    effects: [
      { kind: 'damage', amount: 7 },
      { kind: 'conditional', condition: { kind: 'after_type', type: 'power' }, then: [{ kind: 'damage', amount: 6 }] },
    ],
  },
  n_drone_fury: {
    id: 'n_drone_fury',
    name: '총력 가동',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: '데미지 = 3 × 이번 전투 누적 공격 수.',
    effects: [{ kind: 'damage_per_attack', amount: 3 }],
  },

  // ── 풀 확장 (공학자) ──────────────────────────────────────
  n_bolt: {
    id: 'n_bolt',
    name: '볼트',
    type: 'attack', rarity: 'common', cost: 0, target: 'enemy',
    description: '4 데미지.',
    effects: [{ kind: 'damage', amount: 4 }],
  },
  n_combo_strike: {
    id: 'n_combo_strike',
    name: '연계 타격',
    type: 'attack', rarity: 'uncommon', cost: 1, target: 'enemy',
    description: '5 데미지 2회. 직전이 공격이면 +5 데미지.',
    effects: [
      { kind: 'damage', amount: 5, times: 2 },
      { kind: 'conditional', condition: { kind: 'after_type', type: 'attack' }, then: [{ kind: 'damage', amount: 5 }] },
    ],
  },
  n_counter: {
    id: 'n_counter',
    name: '대응 사격',
    type: 'attack', rarity: 'uncommon', cost: 1, target: 'enemy',
    description: '8 데미지. 가시 +3.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'apply_self', status: 'thorns', amount: 3 },
    ],
  },
  n_overload: {
    id: 'n_overload',
    name: '과부하',
    type: 'attack', rarity: 'uncommon', cost: 1, target: 'all_enemies',
    description: 'HP -4. 모든 적에게 10 데미지.',
    effects: [
      { kind: 'lose_hp', amount: 4 },
      { kind: 'damage_all', amount: 10 },
    ],
  },
  n_railgun: {
    id: 'n_railgun',
    name: '레일건',
    type: 'attack', rarity: 'rare', cost: 2, target: 'enemy',
    description: '18 데미지 2회. 소멸.',
    effects: [{ kind: 'damage', amount: 18, times: 2 }],
    exhaust: true,
  },
  n_final_count: {
    id: 'n_final_count',
    name: '최종 카운트',
    type: 'attack', rarity: 'rare', cost: 2, target: 'enemy',
    description: '데미지 = 4 × 이번 턴 사용한 카드 수. 소멸.',
    effects: [{ kind: 'damage_per_card_this_turn', amount: 4 }],
    exhaust: true,
  },
};

const ENGINEER_UPGRADE_MAP: Record<string, Partial<CardDef>> = {
  n_wrench:         { name: '렌치 타격+',       description: '9 데미지.',                              effects: [{ kind: 'damage', amount: 9 }] },
  n_shield_gen:     { name: '에너지 실드+',     description: '방어도 +8.',                             effects: [{ kind: 'block', amount: 8 }] },
  n_light_drone:   { name: '경량 드론+',       description: '드론 배치: 매턴 랜덤 적에게 9 데미지.', effects: [{ kind: 'apply_self', status: 'drone_basic', amount: 9 }] },
  n_shrapnel:       { name: '파편 투사+',       description: '모든 적에게 11 데미지.',                 effects: [{ kind: 'damage_all', amount: 11 }] },
  n_rivet:          { name: '리벳건+',          description: '7 데미지를 두 번.',                      effects: [{ kind: 'damage', amount: 7, times: 2 }] },
  n_overclock:      { name: '오버클럭+',        description: '힘 +4.',                                 effects: [{ kind: 'apply_self', status: 'strength', amount: 4 }] },
  n_repair:         { name: '수리 도구+',       description: '방어도 +11. 1장 드로우.',                effects: [{ kind: 'block', amount: 11 }, { kind: 'draw', amount: 1 }] },
  n_mag_field:      { name: '자기장 방벽+',     description: '방어도 +9. 무작위 카드 1장 소멸.',       effects: [{ kind: 'block', amount: 9 }, { kind: 'exhaust_random_hand' }] },
  n_emp:            { name: '전자기 충격+',     description: '14 데미지. 빙결 +1.',                    effects: [{ kind: 'damage', amount: 14 }, { kind: 'apply_enemy', status: 'freeze', amount: 1 }] },
  n_spark:          { name: '스파크+',          description: '10 데미지. 2장 드로우.',                 effects: [{ kind: 'damage', amount: 10 }, { kind: 'draw', amount: 2 }] },
  n_plating:        { name: '장갑 도금+',       description: '7 데미지. 방어도 +7.',                   effects: [{ kind: 'damage', amount: 7 }, { kind: 'block', amount: 7 }] },
  n_beam:           { name: '집속 빔+',         description: '모든 적에게 7 데미지. 취약 +1.',         effects: [{ kind: 'damage_all', amount: 7 }, { kind: 'apply_all', status: 'vulnerable', amount: 1 }] },
  n_heavy_drone:   { name: '중형 드론+',       description: '드론 배치: 2턴마다 랜덤 적에게 16 데미지.', effects: [{ kind: 'apply_self', status: 'drone_heavy', amount: 16 }] },
  n_frost_drone:   { name: '냉각 드론+',       description: '드론 배치: 2턴마다 랜덤 적에게 빙결 +2.', effects: [{ kind: 'apply_self', status: 'drone_ice', amount: 2 }] },
  n_flame_drone:   { name: '화염 드론+',       description: '드론 배치: 매턴 랜덤 적에게 화상 +4.',   effects: [{ kind: 'apply_self', status: 'drone_burn', amount: 4 }] },
  n_eject:          { name: '긴급 탈출+',       description: 'HP -2. 에너지 +3.',                      effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'energy', amount: 3 }] },
  n_barrier:        { name: '방벽 생성기+',     description: '방어도 +13.',                            effects: [{ kind: 'block', amount: 13 }] },
  n_acid:           { name: '산성탄+',          description: '7 데미지. 중독 +7.',                     effects: [{ kind: 'damage', amount: 7 }, { kind: 'apply_enemy', status: 'poison', amount: 7 }] },
  n_auto_repair:    { name: '자동 수리+',       description: '재생 +8.',                               effects: [{ kind: 'apply_self', status: 'regen', amount: 8 }] },
  n_reinforce:      { name: '강화 코팅+',       description: '턴 종료 시 방어도 +4.',                  effects: [{ kind: 'apply_self', status: 'metallicize', amount: 4 }] },
  n_power_surge:    { name: '동력 증폭+',       description: '힘 +3.',                                 effects: [{ kind: 'apply_self', status: 'strength', amount: 3 }] },
  n_chain_bomb:     { name: '연쇄 폭탄+',       description: '10 데미지. 사용할 때마다 영구 데미지 +3.', effects: [{ kind: 'damage', amount: 10 }], scaling: { kind: 'on_play', amount: 3 } },
  n_siege_drone:   { name: '공성 드론+',       description: '드론 배치: 3턴마다 모든 적에게 14 데미지.', effects: [{ kind: 'apply_self', status: 'drone_aoe', amount: 14 }] },
  n_tesla:          { name: '테슬라 코일+',     description: '42 데미지. 취약 +3.',                    effects: [{ kind: 'damage', amount: 42 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  n_meltdown:       { name: '노심 용해+',       description: 'HP -3. 24 데미지.',                      effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage', amount: 24 }] },
  n_perpetual:      { name: '영구 기관+',       description: '턴 시작 시 힘 +3. 선천.',                effects: [{ kind: 'apply_self', status: 'ritual', amount: 3 }] },
  // 콤보 시너지
  n_precise:        { name: '정밀 타격+',       description: '11 데미지. 이번 턴 첫 카드면 +11 데미지.',
                      effects: [{ kind: 'damage', amount: 11 }, { kind: 'conditional', condition: { kind: 'first_this_turn' }, then: [{ kind: 'damage', amount: 11 }] }] },
  n_chain_reaction: { name: '연쇄 반응+',       description: '10 데미지. 직전이 효과카드면 +9 데미지.',
                      effects: [{ kind: 'damage', amount: 10 }, { kind: 'conditional', condition: { kind: 'after_type', type: 'power' }, then: [{ kind: 'damage', amount: 9 }] }] },
  n_drone_fury:    { name: '총력 가동+',       description: '데미지 = 4 × 이번 전투 누적 공격 수.',
                      effects: [{ kind: 'damage_per_attack', amount: 4 }] },
  // 풀 확장
  n_bolt:           { name: '볼트+',            description: '6 데미지.',                              effects: [{ kind: 'damage', amount: 6 }] },
  n_combo_strike:   { name: '연계 타격+',       description: '7 데미지 2회. 직전이 공격이면 +7 데미지.',
                      effects: [{ kind: 'damage', amount: 7, times: 2 }, { kind: 'conditional', condition: { kind: 'after_type', type: 'attack' }, then: [{ kind: 'damage', amount: 7 }] }] },
  n_counter:        { name: '대응 사격+',       description: '11 데미지. 가시 +5.',                    effects: [{ kind: 'damage', amount: 11 }, { kind: 'apply_self', status: 'thorns', amount: 5 }] },
  n_overload:       { name: '과부하+',          description: 'HP -3. 모든 적에게 14 데미지.',          effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage_all', amount: 14 }] },
  n_railgun:        { name: '레일건+',          description: '22 데미지 2회. 소멸.',                   effects: [{ kind: 'damage', amount: 22, times: 2 }] },
  n_final_count:    { name: '최종 카운트+',     description: '데미지 = 5 × 이번 턴 사용한 카드 수. 소멸.', effects: [{ kind: 'damage_per_card_this_turn', amount: 5 }] },
};

export function engineerGetEffectiveDef(card: CardInstance): CardDef {
  const base = ENGINEER_CARD_DEFS[card.defId];
  if (!card.upgraded) return base;
  const up = ENGINEER_UPGRADE_MAP[card.defId];
  return up ? { ...base, ...up } : base;
}

export function canUpgradeEngineer(card: CardInstance): boolean {
  return (card.upgraded ?? 0) < 2 && card.defId in ENGINEER_UPGRADE_MAP;
}

const ENGINEER_CARD_LIST = Object.values(ENGINEER_CARD_DEFS);
export const ENGINEER_COMMON_CARDS   = ENGINEER_CARD_LIST.filter((c) => c.rarity === 'common');
export const ENGINEER_UNCOMMON_CARDS = ENGINEER_CARD_LIST.filter((c) => c.rarity === 'uncommon');
export const ENGINEER_RARE_CARDS     = ENGINEER_CARD_LIST.filter((c) => c.rarity === 'rare');
