import type { CardDef, CardInstance } from '../types';

export const FIGHTER_CARD_DEFS: Record<string, CardDef> = {
  // ── Starter ──
  f_quick_kick: {
    id: 'f_quick_kick',
    name: '질풍각',
    type: 'attack',
    rarity: 'starter',
    cost: 1,
    target: 'enemy',
    description: '6 데미지.',
    effects: [{ kind: 'damage', amount: 6 }],
  },
  f_nen_guard: {
    id: 'f_nen_guard',
    name: '철금강',
    type: 'skill',
    rarity: 'starter',
    cost: 1,
    target: 'self',
    description: '방어도 +5.',
    effects: [{ kind: 'block', amount: 5 }],
  },

  // ── Common (includes starter-special) ──
  f_upper_kick: {
    id: 'f_upper_kick',
    name: '무즈 어퍼',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'enemy',
    description: '8 데미지. 취약 +2.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
  },
  f_low_kick: {
    id: 'f_low_kick',
    name: '로킥',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '5 데미지를 두 번.',
    effects: [{ kind: 'damage', amount: 5, times: 2 }],
  },
  f_aerial_stomp: {
    id: 'f_aerial_stomp',
    name: '공중 밟기',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 8 데미지.',
    effects: [{ kind: 'damage_all', amount: 8 }],
  },
  f_dragon_kick: {
    id: 'f_dragon_kick',
    name: '호신연격',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 4 데미지. 취약 +1.',
    effects: [
      { kind: 'damage_all', amount: 4 },
      { kind: 'apply_all', status: 'vulnerable', amount: 1 },
    ],
  },
  f_heavy_punch: {
    id: 'f_heavy_punch',
    name: '해머 킥',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'enemy',
    description: '11 데미지. 빙결 +1.',
    effects: [
      { kind: 'damage', amount: 11 },
      { kind: 'apply_enemy', status: 'freeze', amount: 1 },
    ],
  },
  f_combo: {
    id: 'f_combo',
    name: '호포',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '9 데미지. 1장 드로우.',
    effects: [
      { kind: 'damage', amount: 9 },
      { kind: 'draw', amount: 1 },
    ],
  },
  f_nen_bullet: {
    id: 'f_nen_bullet',
    name: '넨탄',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'random_enemy',
    description: '4 데미지를 세 번.',
    effects: [{ kind: 'damage', amount: 4, times: 3 }],
  },
  f_iron_body: {
    id: 'f_iron_body',
    name: '헬터 스켈터',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '5 데미지. 방어도 +5.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'block', amount: 5 },
    ],
  },
  f_ki_focus: {
    id: 'f_ki_focus',
    name: '크라우치',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  f_dodge: {
    id: 'f_dodge',
    name: '분신',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '방어도 +8. 1장 드로우.',
    effects: [
      { kind: 'block', amount: 8 },
      { kind: 'draw', amount: 1 },
    ],
  },
  f_focus: {
    id: 'f_focus',
    name: '수플렉스',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '방어도 +7. 무작위 카드 1장 소멸.',
    effects: [
      { kind: 'block', amount: 7 },
      { kind: 'exhaust_random_hand' },
    ],
  },

  // ── Uncommon ──
  f_needle_throw: {
    id: 'f_needle_throw',
    name: '독바르기',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '5 데미지. 중독 +5.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'apply_enemy', status: 'poison', amount: 5 },
    ],
  },
  f_lion_roar: {
    id: 'f_lion_roar',
    name: '금강쇄',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'enemy',
    description: '13 데미지. 취약 +1. 약화 +1.',
    effects: [
      { kind: 'damage', amount: 13 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 1 },
      { kind: 'apply_enemy', status: 'weak', amount: 1 },
    ],
  },
  f_snap_shot: {
    id: 'f_snap_shot',
    name: '넥 스냅',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    target: 'self',
    description: 'HP -3. 에너지 +2.',
    effects: [
      { kind: 'lose_hp', amount: 3 },
      { kind: 'energy', amount: 2 },
    ],
  },
  f_slide_grab: {
    id: 'f_slide_grab',
    name: '붕권',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '방어도 +10. (이번 턴 한정)',
    effects: [{ kind: 'block', amount: 10 }],
    ethereal: true,
  },
  f_hadouken: {
    id: 'f_hadouken',
    name: '수플렉스 썬더',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  f_mount: {
    id: 'f_mount',
    name: '일발화약성',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    target: 'self',
    description: '재생 +5.',
    effects: [{ kind: 'apply_self', status: 'regen', amount: 5 }],
  },
  f_double_open: {
    id: 'f_double_open',
    name: '이중개방',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '턴 종료 시 방어도 +3.',
    effects: [{ kind: 'apply_self', status: 'metallicize', amount: 3 }],
  },
  f_saro_hwanyeol: {
    id: 'f_saro_hwanyeol',
    name: '사로지환열',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '8 데미지. 사용할 때마다 영구 데미지 +2.',
    effects: [{ kind: 'damage', amount: 8 }],
    scaling: { kind: 'on_play', amount: 2 },
  },
  f_red_dragon: {
    id: 'f_red_dragon',
    name: '적룡노화',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '카드 소멸 시 방어도 +3.',
    effects: [{ kind: 'apply_self', status: 'on_exhaust_block', amount: 3 }],
  },

  // ── Rare (1차 각성기) ──
  f_golden_thunder: {
    id: 'f_golden_thunder',
    name: '금뇌호 : 심판의 넨수',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'enemy',
    description: '32 데미지. 취약 +2.',
    effects: [
      { kind: 'damage', amount: 32 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
  },
  f_flame_kick: {
    id: 'f_flame_kick',
    name: '화염의 각',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 21 데미지.',
    effects: [{ kind: 'damage_all', amount: 21 }],
  },
  f_sky_fall: {
    id: 'f_sky_fall',
    name: '천붕지괴',
    type: 'power',
    rarity: 'rare',
    cost: 3,
    target: 'self',
    description: '턴 시작 시 힘 +2. 선천.',
    effects: [{ kind: 'apply_self', status: 'ritual', amount: 2 }],
    innate: true,
  },
  f_my_rhythm: {
    id: 'f_my_rhythm',
    name: '나의 공격 리듬은!!',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: 'HP -5. 18 데미지.',
    effects: [
      { kind: 'lose_hp', amount: 5 },
      { kind: 'damage', amount: 18 },
    ],
    exhaust: true,
  },

  // ── 격투가 콤보 시너지 ─────────────────────────────────────
  f_focused_strike: {
    id: 'f_focused_strike',
    name: '집중타',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '8 데미지. 이번 턴 첫 카드면 +8 데미지.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'conditional', condition: { kind: 'first_this_turn' }, then: [{ kind: 'damage', amount: 8 }] },
    ],
  },
  f_combo_punch: {
    id: 'f_combo_punch',
    name: '콤보 펀치',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '7 데미지. 직전이 공격이면 +6 데미지.',
    effects: [
      { kind: 'damage', amount: 7 },
      { kind: 'conditional', condition: { kind: 'after_type', type: 'attack' }, then: [{ kind: 'damage', amount: 6 }] },
    ],
  },
  f_dragon_fury: {
    id: 'f_dragon_fury',
    name: '용의 분노',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: '데미지 = 3 × 이번 전투 누적 공격 수.',
    effects: [{ kind: 'damage_per_attack', amount: 3 }],
  },

  // ── 풀 확장 (격투가) ──────────────────────────────────────
  f_jab: {
    id: 'f_jab',
    name: '잽',
    type: 'attack', rarity: 'common', cost: 0, target: 'enemy',
    description: '4 데미지.',
    effects: [{ kind: 'damage', amount: 4 }],
  },
  f_combination: {
    id: 'f_combination',
    name: '콤비네이션',
    type: 'attack', rarity: 'uncommon', cost: 1, target: 'enemy',
    description: '5 데미지 2회. 직전이 공격이면 +5 데미지.',
    effects: [
      { kind: 'damage', amount: 5, times: 2 },
      { kind: 'conditional', condition: { kind: 'after_type', type: 'attack' }, then: [{ kind: 'damage', amount: 5 }] },
    ],
  },
  f_counter: {
    id: 'f_counter',
    name: '카운터',
    type: 'attack', rarity: 'uncommon', cost: 1, target: 'enemy',
    description: '8 데미지. 가시 +3.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'apply_self', status: 'thorns', amount: 3 },
    ],
  },
  f_rage_burst: {
    id: 'f_rage_burst',
    name: '분노 폭발',
    type: 'attack', rarity: 'uncommon', cost: 1, target: 'all_enemies',
    description: 'HP -4. 모든 적에게 10 데미지.',
    effects: [
      { kind: 'lose_hp', amount: 4 },
      { kind: 'damage_all', amount: 10 },
    ],
  },
  f_shadow_kick: {
    id: 'f_shadow_kick',
    name: '무영각',
    type: 'attack', rarity: 'rare', cost: 2, target: 'enemy',
    description: '18 데미지 2회. 소멸.',
    effects: [{ kind: 'damage', amount: 18, times: 2 }],
    exhaust: true,
  },
  f_ten_count: {
    id: 'f_ten_count',
    name: '텐 카운트',
    type: 'attack', rarity: 'rare', cost: 2, target: 'enemy',
    description: '데미지 = 4 × 이번 턴 사용한 카드 수. 소멸.',
    effects: [{ kind: 'damage_per_card_this_turn', amount: 4 }],
    exhaust: true,
  },
};

const FIGHTER_UPGRADE_MAP: Record<string, Partial<CardDef>> = {
  f_quick_kick:    { name: '질풍각+',                   description: '9 데미지.',                              effects: [{ kind: 'damage', amount: 9 }] },
  f_nen_guard:     { name: '철금강+',                  description: '방어도 +8.',                            effects: [{ kind: 'block', amount: 8 }] },
  f_upper_kick:    { name: '무즈 어퍼+',                 description: '10 데미지. 취약 +3.',                   effects: [{ kind: 'damage', amount: 10 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  f_low_kick:      { name: '로킥+',                     description: '7 데미지를 두 번.',                     effects: [{ kind: 'damage', amount: 7, times: 2 }] },
  f_aerial_stomp:  { name: '공중 밟기+',                description: '모든 적에게 11 데미지.',                effects: [{ kind: 'damage_all', amount: 11 }] },
  f_dragon_kick:   { name: '호신연격+',                     description: '모든 적에게 7 데미지. 취약 +1.',        effects: [{ kind: 'damage_all', amount: 7 }, { kind: 'apply_all', status: 'vulnerable', amount: 1 }] },
  f_heavy_punch:   { name: '해머 킥+',                description: '14 데미지. 빙결 +1.',                  effects: [{ kind: 'damage', amount: 14 }, { kind: 'apply_enemy', status: 'freeze', amount: 1 }] },
  f_combo:         { name: '호포+',                description: '10 데미지. 2장 드로우.',                effects: [{ kind: 'damage', amount: 10 }, { kind: 'draw', amount: 2 }] },
  f_nen_bullet:    { name: '넨탄+',                    description: '5 데미지를 세 번.',                     effects: [{ kind: 'damage', amount: 5, times: 3 }] },
  f_iron_body:     { name: '헬터 스켈터+',                description: '7 데미지. 방어도 +7.',                  effects: [{ kind: 'damage', amount: 7 }, { kind: 'block', amount: 7 }] },
  f_ki_focus:      { name: '크라우치+',                  description: '힘 +4.',                                effects: [{ kind: 'apply_self', status: 'strength', amount: 4 }] },
  f_dodge:         { name: '분신+',                     description: '방어도 +11. 1장 드로우.',               effects: [{ kind: 'block', amount: 11 }, { kind: 'draw', amount: 1 }] },
  f_focus:         { name: '수플렉스+',                     description: '방어도 +9. 무작위 카드 1장 소멸.',      effects: [{ kind: 'block', amount: 9 }, { kind: 'exhaust_random_hand' }] },
  f_needle_throw:  { name: '독바르기+',                description: '7 데미지. 중독 +7.',                    effects: [{ kind: 'damage', amount: 7 }, { kind: 'apply_enemy', status: 'poison', amount: 7 }] },
  f_lion_roar:     { name: '금강쇄+',                   description: '15 데미지. 취약 +2. 약화 +2.',          effects: [{ kind: 'damage', amount: 15 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 2 }, { kind: 'apply_enemy', status: 'weak', amount: 2 }] },
  f_snap_shot:     { name: '넥 스냅+',                  description: 'HP -2. 에너지 +3.',                     effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'energy', amount: 3 }] },
  f_slide_grab:    { name: '붕권+',            description: '방어도 +13.',                           effects: [{ kind: 'block', amount: 13 }] },
  f_hadouken:      { name: '수플렉스 썬더+',                   description: '힘 +3.',                                effects: [{ kind: 'apply_self', status: 'strength', amount: 3 }] },
  f_mount:         { name: '일발화약성+',                   description: '재생 +8.',                              effects: [{ kind: 'apply_self', status: 'regen', amount: 8 }] },
  f_double_open:   { name: '이중개방+',                 description: '턴 종료 시 방어도 +4.',                 effects: [{ kind: 'apply_self', status: 'metallicize', amount: 4 }] },
  f_saro_hwanyeol: { name: '사로지환열+',                description: '10 데미지. 사용할 때마다 영구 데미지 +3.', effects: [{ kind: 'damage', amount: 10 }] },
  f_red_dragon:    { name: '적룡노화+',                  description: '카드 소멸 시 방어도 +5.',                effects: [{ kind: 'apply_self', status: 'on_exhaust_block', amount: 5 }] },
  f_golden_thunder: { name: '금뇌호 : 심판의 넨수+',   description: '42 데미지. 취약 +3.',                   effects: [{ kind: 'damage', amount: 42 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  f_flame_kick:    { name: '화염의 각+',                description: '모든 적에게 28 데미지.',                effects: [{ kind: 'damage_all', amount: 28 }] },
  f_sky_fall:      { name: '천붕지괴+',                 description: '턴 시작 시 힘 +3. 선천.',               effects: [{ kind: 'apply_self', status: 'ritual', amount: 3 }] },
  f_my_rhythm:     { name: '나의 공격 리듬은!!+',       description: 'HP -3. 24 데미지.',                     effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage', amount: 24 }] },
  // 콤보 시너지
  f_focused_strike: { name: '집중타+',   description: '11 데미지. 이번 턴 첫 카드면 +11 데미지.',
                       effects: [{ kind: 'damage', amount: 11 }, { kind: 'conditional', condition: { kind: 'first_this_turn' }, then: [{ kind: 'damage', amount: 11 }] }] },
  f_combo_punch:    { name: '콤보 펀치+', description: '10 데미지. 직전이 공격이면 +9 데미지.',
                       effects: [{ kind: 'damage', amount: 10 }, { kind: 'conditional', condition: { kind: 'after_type', type: 'attack' }, then: [{ kind: 'damage', amount: 9 }] }] },
  f_dragon_fury:    { name: '용의 분노+', description: '데미지 = 4 × 이번 전투 누적 공격 수.',
                       effects: [{ kind: 'damage_per_attack', amount: 4 }] },
  // 풀 확장
  f_jab:            { name: '잽+',         description: '6 데미지.',                              effects: [{ kind: 'damage', amount: 6 }] },
  f_combination:    { name: '콤비네이션+',  description: '7 데미지 2회. 직전이 공격이면 +7 데미지.',
                       effects: [{ kind: 'damage', amount: 7, times: 2 }, { kind: 'conditional', condition: { kind: 'after_type', type: 'attack' }, then: [{ kind: 'damage', amount: 7 }] }] },
  f_counter:        { name: '카운터+',      description: '11 데미지. 가시 +5.',                    effects: [{ kind: 'damage', amount: 11 }, { kind: 'apply_self', status: 'thorns', amount: 5 }] },
  f_rage_burst:     { name: '분노 폭발+',   description: 'HP -3. 모든 적에게 14 데미지.',          effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage_all', amount: 14 }] },
  f_shadow_kick:    { name: '무영각+',      description: '22 데미지 2회. 소멸.',                   effects: [{ kind: 'damage', amount: 22, times: 2 }] },
  f_ten_count:      { name: '텐 카운트+',   description: '데미지 = 5 × 이번 턴 사용한 카드 수. 소멸.', effects: [{ kind: 'damage_per_card_this_turn', amount: 5 }] },
};

export function fighterGetEffectiveDef(card: CardInstance): CardDef {
  const base = FIGHTER_CARD_DEFS[card.defId];
  if (!card.upgraded) return base;
  const up = FIGHTER_UPGRADE_MAP[card.defId];
  return up ? { ...base, ...up } : base;
}

export function canUpgradeFighter(card: CardInstance): boolean {
  return (card.upgraded ?? 0) < 2 && card.defId in FIGHTER_UPGRADE_MAP;
}

const FIGHTER_CARD_LIST = Object.values(FIGHTER_CARD_DEFS);
export const FIGHTER_COMMON_CARDS   = FIGHTER_CARD_LIST.filter((c) => c.rarity === 'common');
export const FIGHTER_UNCOMMON_CARDS = FIGHTER_CARD_LIST.filter((c) => c.rarity === 'uncommon');
export const FIGHTER_RARE_CARDS     = FIGHTER_CARD_LIST.filter((c) => c.rarity === 'rare');
