import type { CardDef, CardInstance } from '../types';

export const GUNNER_CARD_DEFS: Record<string, CardDef> = {
  // ── Starter ──
  g_rising_shot: {
    id: 'g_rising_shot',
    name: '속사',
    type: 'attack',
    rarity: 'starter',
    cost: 1,
    target: 'enemy',
    description: '6 데미지.',
    effects: [{ kind: 'damage', amount: 6 }],
  },
  g_reload: {
    id: 'g_reload',
    name: '긴급 회피',
    type: 'skill',
    rarity: 'starter',
    cost: 1,
    target: 'self',
    description: '방어도 +5.',
    effects: [{ kind: 'block', amount: 5 }],
  },

  // ── Common attacks ──
  g_headshot: {
    id: 'g_headshot',
    name: '산탄',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'enemy',
    description: '8 데미지. 취약 +2.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
  },
  g_double_gunhawk: {
    id: 'g_double_gunhawk',
    name: '이중 사격',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '5 데미지를 두 번.',
    effects: [{ kind: 'damage', amount: 5, times: 2 }],
  },
  g_western_fire: {
    id: 'g_western_fire',
    name: '난사',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 8 데미지.',
    effects: [{ kind: 'damage_all', amount: 8 }],
  },
  g_frag: {
    id: 'g_frag',
    name: '섬광탄',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 4 데미지. 취약 +1.',
    effects: [
      { kind: 'damage_all', amount: 4 },
      { kind: 'apply_all', status: 'vulnerable', amount: 1 },
    ],
  },
  g_cannonball: {
    id: 'g_cannonball',
    name: '연사포',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'enemy',
    description: '14 데미지.',
    effects: [{ kind: 'damage', amount: 14 }],
  },
  g_burst_fire: {
    id: 'g_burst_fire',
    name: '응징',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '9 데미지. 1장 드로우.',
    effects: [
      { kind: 'damage', amount: 9 },
      { kind: 'draw', amount: 1 },
    ],
  },
  g_barrage: {
    id: 'g_barrage',
    name: '공중사격',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '4 데미지를 세 번.',
    effects: [{ kind: 'damage', amount: 4, times: 3 }],
  },

  // ── Common skills ──
  g_smoke: {
    id: 'g_smoke',
    name: '연막 사격',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 약화 +2.',
    effects: [{ kind: 'apply_all', status: 'weak', amount: 2 }],
  },
  g_booster: {
    id: 'g_booster',
    name: '전투 집중',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  g_reposit: {
    id: 'g_reposit',
    name: '지뢰 설치',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '방어도 +8. 1장 드로우.',
    effects: [
      { kind: 'block', amount: 8 },
      { kind: 'draw', amount: 1 },
    ],
  },
  g_ammo: {
    id: 'g_ammo',
    name: '조준 사격',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: '1장 드로우. 무작위 카드 1장 소멸.',
    effects: [
      { kind: 'draw', amount: 1 },
      { kind: 'exhaust_random_hand' },
    ],
    exhaust: true,
  },
  g_armor: {
    id: 'g_armor',
    name: '빙결탄',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '5 데미지. 빙결 +1. 소멸.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'apply_enemy', status: 'freeze', amount: 1 },
    ],
    exhaust: true,
  },

  // ── Rare ──
  g_satellite: {
    id: 'g_satellite',
    name: '하늘의 빛줄기',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 18 데미지. 약화 +2.',
    effects: [
      { kind: 'damage_all', amount: 18 },
      { kind: 'apply_all', status: 'weak', amount: 2 },
    ],
  },
  g_viper: {
    id: 'g_viper',
    name: '불꽃 연격',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '5 데미지. 중독 +5.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'apply_enemy', status: 'poison', amount: 5 },
    ],
  },
  g_optical: {
    id: 'g_optical',
    name: '중저격총',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    target: 'self',
    description: 'HP -3. 에너지 +2.',
    effects: [
      { kind: 'lose_hp', amount: 3 },
      { kind: 'energy', amount: 2 },
    ],
  },
  g_napalm: {
    id: 'g_napalm',
    name: '화염방사기',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 8 데미지. 직전이 효과카드면 화상 +3.',
    effects: [
      { kind: 'damage_all', amount: 8 },
      { kind: 'conditional', condition: { kind: 'after_type', type: 'power' }, then: [{ kind: 'apply_all', status: 'burn', amount: 3 }] },
    ],
    exhaust: true,
  },
  g_g14: {
    id: 'g_g14',
    name: '파열 수류탄',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '8 데미지. 취약 +2.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
  },
  g_reinforce: {
    id: 'g_reinforce',
    name: '대전차포',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  g_sparrow: {
    id: 'g_sparrow',
    name: '자폭 기계',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '턴 종료 시 방어도 +3.',
    effects: [{ kind: 'apply_self', status: 'metallicize', amount: 3 }],
  },
  g_gods_hail: {
    id: 'g_gods_hail',
    name: '강철의 비',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '6 데미지. 사용할 때마다 영구 데미지 +2.',
    effects: [{ kind: 'damage', amount: 6 }],
    scaling: { kind: 'on_play', amount: 2 },
  },
  g_divergent: {
    id: 'g_divergent',
    name: '확산탄',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '카드 소멸 시 카드 1장 드로우.',
    effects: [{ kind: 'apply_self', status: 'on_exhaust_draw', amount: 1 }],
  },

  // ── Rare (1차 각성기) ──
  g_overheat: {
    id: 'g_overheat',
    name: '집중 제압',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'enemy',
    description: '32 데미지. 취약 +2. 유지.',
    effects: [
      { kind: 'damage', amount: 32 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
    retain: true,
  },
  g_mech_drop: {
    id: 'g_mech_drop',
    name: '시한폭탄',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: '26 데미지.',
    effects: [{ kind: 'damage', amount: 26 }],
  },
  g_arms_dealer: {
    id: 'g_arms_dealer',
    name: '결사 사격',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: 'HP -5. 22 데미지.',
    effects: [
      { kind: 'lose_hp', amount: 5 },
      { kind: 'damage', amount: 22 },
    ],
    exhaust: true,
  },
  g_airstrike: {
    id: 'g_airstrike',
    name: '폭풍 사격',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 18 데미지.',
    effects: [{ kind: 'damage_all', amount: 18 }],
    exhaust: true,
  },

  // ── 사수 콤보 시너지 ─────────────────────────────────────
  g_rapid_fire: {
    id: 'g_rapid_fire',
    name: '연사',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '3 데미지 2회. 이번 턴 3번째 이후 카드면 +6 데미지 추가.',
    effects: [
      { kind: 'damage', amount: 3, times: 2 },
      { kind: 'conditional', condition: { kind: 'nth_or_more', n: 3 }, then: [{ kind: 'damage', amount: 6 }] },
    ],
  },
  g_carpet_bomb: {
    id: 'g_carpet_bomb',
    name: '융단폭격',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 7 데미지. 이번 턴 2번째 이후 카드면 +5 데미지.',
    effects: [
      { kind: 'damage_all', amount: 7 },
      { kind: 'conditional', condition: { kind: 'nth_or_more', n: 2 }, then: [{ kind: 'damage_all', amount: 5 }] },
    ],
  },
  g_overdrive: {
    id: 'g_overdrive',
    name: '오버드라이브',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: '데미지 = 3 × 이번 전투 누적 공격 수.',
    effects: [{ kind: 'damage_per_attack', amount: 3 }],
  },

  // ── 풀 확장 (사수) ────────────────────────────────────────
  g_smoke_grenade: {
    id: 'g_smoke_grenade',
    name: '연막탄',
    type: 'skill', rarity: 'common', cost: 1, target: 'self',
    description: '방어도 +6. 모든 적 약화 +1.',
    effects: [
      { kind: 'block', amount: 6 },
      { kind: 'apply_all', status: 'weak', amount: 1 },
    ],
  },
  g_sniper: {
    id: 'g_sniper',
    name: '저격수',
    type: 'attack', rarity: 'uncommon', cost: 2, target: 'enemy',
    description: '18 데미지. 약화 +2.',
    effects: [
      { kind: 'damage', amount: 18 },
      { kind: 'apply_enemy', status: 'weak', amount: 2 },
    ],
  },
  g_grenade_launcher: {
    id: 'g_grenade_launcher',
    name: '유탄발사기',
    type: 'attack', rarity: 'uncommon', cost: 2, target: 'all_enemies',
    description: '모든 적에게 12 데미지. 약화 +1. 소멸.',
    effects: [
      { kind: 'damage_all', amount: 12 },
      { kind: 'apply_all', status: 'weak', amount: 1 },
    ],
    exhaust: true,
  },
  g_kevlar: {
    id: 'g_kevlar',
    name: '방탄조끼',
    type: 'skill', rarity: 'uncommon', cost: 1, target: 'self',
    description: '방어도 +8. 가시 +3.',
    effects: [
      { kind: 'block', amount: 8 },
      { kind: 'apply_self', status: 'thorns', amount: 3 },
    ],
  },
  g_helios: {
    id: 'g_helios',
    name: '최종 병기',
    type: 'attack', rarity: 'rare', cost: 3, target: 'enemy',
    description: '35 데미지. 모든 적 약화 +2. 소멸.',
    effects: [
      { kind: 'damage', amount: 35 },
      { kind: 'apply_all', status: 'weak', amount: 2 },
    ],
    exhaust: true,
  },
};

const GUNNER_UPGRADE_MAP: Record<string, Partial<CardDef>> = {
  g_rising_shot:    { name: '속사+',       description: '9 데미지.',                        effects: [{ kind: 'damage', amount: 9 }] },
  g_reload:         { name: '슬라이딩+',      description: '방어도 +8.',                       effects: [{ kind: 'block', amount: 8 }] },
  g_headshot:       { name: '산탄+',           description: '10 데미지. 취약 +3.',              effects: [{ kind: 'damage', amount: 10 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  g_double_gunhawk: { name: '발차기+',      description: '7 데미지를 두 번.',                effects: [{ kind: 'damage', amount: 7, times: 2 }] },
  g_western_fire:   { name: '회전 킥+',    description: '모든 적에게 11 데미지.',           effects: [{ kind: 'damage_all', amount: 11 }] },
  g_frag:           { name: '연속 회전+',         description: '모든 적에게 7 데미지. 취약 +1.',   effects: [{ kind: 'damage_all', amount: 7 }, { kind: 'apply_all', status: 'vulnerable', amount: 1 }] },
  g_cannonball:     { name: '연사포+',           description: '18 데미지.',                       effects: [{ kind: 'damage', amount: 18 }] },
  g_burst_fire:     { name: '응징+',        description: '10 데미지. 2장 드로우.',           effects: [{ kind: 'damage', amount: 10 }, { kind: 'draw', amount: 2 }] },
  g_barrage:        { name: '공중사격+',             description: '5 데미지를 세 번.',                effects: [{ kind: 'damage', amount: 5, times: 3 }] },
  g_smoke:          { name: '승천 회전+', description: '모든 적에게 약화 +3.',            effects: [{ kind: 'apply_all', status: 'weak', amount: 3 }] },
  g_booster:        { name: '속사의 극치+',           description: '힘 +4.',                           effects: [{ kind: 'apply_self', status: 'strength', amount: 4 }] },
  g_reposit:        { name: '지뢰 설치+',      description: '방어도 +11. 1장 드로우.',          effects: [{ kind: 'block', amount: 11 }, { kind: 'draw', amount: 1 }] },
  g_ammo:           { name: '조준 사격+',        description: '2장 드로우. 무작위 카드 1장 소멸.',effects: [{ kind: 'draw', amount: 2 }, { kind: 'exhaust_random_hand' }] },
  g_armor:          { name: '빙결탄+',           description: '7 데미지. 빙결 +2. 소멸.',              effects: [{ kind: 'damage', amount: 7 }, { kind: 'apply_enemy', status: 'freeze', amount: 2 }] },
  g_satellite:      { name: '하늘의 빛줄기+',           description: '모든 적에게 24 데미지. 약화 +3.',      effects: [{ kind: 'damage_all', amount: 24 }, { kind: 'apply_all', status: 'weak', amount: 3 }] },
  g_viper:          { name: '불꽃 연격+',                  description: '7 데미지. 중독 +7.',                   effects: [{ kind: 'damage', amount: 7 }, { kind: 'apply_enemy', status: 'poison', amount: 7 }] },
  g_optical:        { name: '중저격총+',       description: 'HP -2. 에너지 +3.',                    effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'energy', amount: 3 }] },
  g_napalm:         { name: '화염방사기+',                description: '모든 적에게 12 데미지. 직전이 효과카드면 화상 +4.',
                      effects: [{ kind: 'damage_all', amount: 12 }, { kind: 'conditional', condition: { kind: 'after_type', type: 'power' }, then: [{ kind: 'apply_all', status: 'burn', amount: 4 }] }] },
  g_g14:            { name: '파열 수류탄+',           description: '11 데미지. 취약 +3.',                  effects: [{ kind: 'damage', amount: 11 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  g_reinforce:      { name: '대전차포+',               description: '힘 +3.',                               effects: [{ kind: 'apply_self', status: 'strength', amount: 3 }] },
  g_sparrow:        { name: '자폭 기계+',         description: '턴 종료 시 방어도 +4.',                effects: [{ kind: 'apply_self', status: 'metallicize', amount: 4 }] },
  g_gods_hail:      { name: '강철의 비+',               description: '8 데미지. 사용할 때마다 영구 데미지 +3.', effects: [{ kind: 'damage', amount: 8 }], scaling: { kind: 'on_play', amount: 3 } },
  g_divergent:      { name: '확산탄+',              description: '카드 소멸 시 카드 2장 드로우.',         effects: [{ kind: 'apply_self', status: 'on_exhaust_draw', amount: 2 }] },
  g_overheat:       { name: '집중 제압+',       description: '42 데미지. 취약 +3. 유지.',            effects: [{ kind: 'damage', amount: 42 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  g_mech_drop:      { name: '시한폭탄+',           description: '34 데미지.',                           effects: [{ kind: 'damage', amount: 34 }] },
  g_arms_dealer:    { name: '발도 사격+',       description: 'HP -3. 30 데미지.',                    effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage', amount: 30 }] },
  g_airstrike:      { name: '마탄+',   description: '모든 적에게 24 데미지.',               effects: [{ kind: 'damage_all', amount: 24 }] },
  // 콤보 시너지
  g_rapid_fire:     { name: '연사+',   description: '4 데미지 2회. 이번 턴 3번째 이후 카드면 +8 데미지 추가.',
                      effects: [{ kind: 'damage', amount: 4, times: 2 }, { kind: 'conditional', condition: { kind: 'nth_or_more', n: 3 }, then: [{ kind: 'damage', amount: 8 }] }] },
  g_carpet_bomb:    { name: '융단폭격+', description: '모든 적에게 10 데미지. 이번 턴 2번째 이후 카드면 +7 데미지.',
                      effects: [{ kind: 'damage_all', amount: 10 }, { kind: 'conditional', condition: { kind: 'nth_or_more', n: 2 }, then: [{ kind: 'damage_all', amount: 7 }] }] },
  g_overdrive:      { name: '오버드라이브+', description: '데미지 = 4 × 이번 전투 누적 공격 수.',
                      effects: [{ kind: 'damage_per_attack', amount: 4 }] },
  // 풀 확장
  g_smoke_grenade:  { name: '연막탄+',        description: '방어도 +9. 모든 적 약화 +2.',          effects: [{ kind: 'block', amount: 9 }, { kind: 'apply_all', status: 'weak', amount: 2 }] },
  g_sniper:         { name: '저격수+',        description: '24 데미지. 약화 +2.',                 effects: [{ kind: 'damage', amount: 24 }, { kind: 'apply_enemy', status: 'weak', amount: 2 }] },
  g_grenade_launcher:{name: '유탄발사기+',    description: '모든 적에게 16 데미지. 약화 +2. 소멸.',effects: [{ kind: 'damage_all', amount: 16 }, { kind: 'apply_all', status: 'weak', amount: 2 }] },
  g_kevlar:         { name: '방탄조끼+',      description: '방어도 +12. 가시 +5.',                effects: [{ kind: 'block', amount: 12 }, { kind: 'apply_self', status: 'thorns', amount: 5 }] },
  g_helios:         { name: '헬리오스+',      description: '45 데미지. 모든 적 약화 +3. 소멸.',   effects: [{ kind: 'damage', amount: 45 }, { kind: 'apply_all', status: 'weak', amount: 3 }] },
};

export function gunnerGetEffectiveDef(card: CardInstance): CardDef {
  const base = GUNNER_CARD_DEFS[card.defId];
  if (!card.upgraded) return base;
  const up = GUNNER_UPGRADE_MAP[card.defId];
  return up ? { ...base, ...up } : base;
}

export function canUpgradeGunner(card: CardInstance): boolean {
  return (card.upgraded ?? 0) < 2 && card.defId in GUNNER_UPGRADE_MAP;
}

const GUNNER_CARD_LIST = Object.values(GUNNER_CARD_DEFS);
export const GUNNER_COMMON_CARDS  = GUNNER_CARD_LIST.filter((c) => c.rarity === 'common');
export const GUNNER_UNCOMMON_CARDS = GUNNER_CARD_LIST.filter((c) => c.rarity === 'uncommon');
export const GUNNER_RARE_CARDS    = GUNNER_CARD_LIST.filter((c) => c.rarity === 'rare');
