import type { CardDef, CardInstance } from '../types';

export const MAGICIAN_CARD_DEFS: Record<string, CardDef> = {
  // ── Starter ──
  m_magic_missile: {
    id: 'm_magic_missile',
    name: '마력 화살',
    type: 'attack',
    rarity: 'starter',
    cost: 1,
    target: 'enemy',
    description: '6 데미지.',
    effects: [{ kind: 'damage', amount: 6 }],
  },
  m_aura_shield: {
    id: 'm_aura_shield',
    name: '마력 방벽',
    type: 'skill',
    rarity: 'starter',
    cost: 1,
    target: 'self',
    description: '방어도 +5.',
    effects: [{ kind: 'block', amount: 5 }],
  },

  // ── Common (starter special + actives) ──
  m_phase_shift: {
    id: 'm_phase_shift',
    name: '차원 전환',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'enemy',
    description: '8 데미지. 취약 +2.',
    effects: [
      { kind: 'damage', amount: 8 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 2 },
    ],
  },
  m_skystrike: {
    id: 'm_skystrike',
    name: '번개 일격',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'enemy',
    description: '14 데미지.',
    effects: [{ kind: 'damage', amount: 14 }],
  },
  m_dragon_tooth: {
    id: 'm_dragon_tooth',
    name: '용의 이빨',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '5 데미지를 두 번.',
    effects: [{ kind: 'damage', amount: 5, times: 2 }],
  },
  m_lantern: {
    id: 'm_lantern',
    name: '화염 등불',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '6 데미지. 화상 +3.',
    effects: [
      { kind: 'damage', amount: 6 },
      { kind: 'apply_enemy', status: 'burn', amount: 3 },
    ],
  },
  m_air_lantern: {
    id: 'm_air_lantern',
    name: '공중 화염',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 8 데미지.',
    effects: [{ kind: 'damage_all', amount: 8 }],
  },
  m_petal: {
    id: 'm_petal',
    name: '꽃잎 폭발',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    description: '모든 적에게 4 데미지. 취약 +1.',
    effects: [
      { kind: 'damage_all', amount: 4 },
      { kind: 'apply_all', status: 'vulnerable', amount: 1 },
    ],
  },

  // ── Common skills ──
  m_pluto: {
    id: 'm_pluto',
    name: '명왕성의 힘',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '5 데미지. 방어도 +5.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'block', amount: 5 },
    ],
  },
  m_frost: {
    id: 'm_frost',
    name: '서리 머리',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '5 데미지. 빙결 +1. 소멸.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'apply_enemy', status: 'freeze', amount: 1 },
    ],
    exhaust: true,
  },
  m_disenchant: {
    id: 'm_disenchant',
    name: '마력 해제',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  m_no_entry: {
    id: 'm_no_entry',
    name: '접근 금지!',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'self',
    description: '방어도 +7. 무작위 카드 1장 소멸.',
    effects: [
      { kind: 'block', amount: 7 },
      { kind: 'exhaust_random_hand' },
    ],
  },
  m_summon_horus: {
    id: 'm_summon_horus',
    name: '소환 : 기갑 골렘',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'self',
    description: '1장 드로우. 무작위 카드 1장 소멸.',
    effects: [
      { kind: 'draw', amount: 1 },
      { kind: 'exhaust_random_hand' },
    ],
    exhaust: true,
  },

  // ── Uncommon ──
  m_blossom: {
    id: 'm_blossom',
    name: '가시 회전',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'enemy',
    description: '13 데미지. 취약 +1. 약화 +1.',
    effects: [
      { kind: 'damage', amount: 13 },
      { kind: 'apply_enemy', status: 'vulnerable', amount: 1 },
      { kind: 'apply_enemy', status: 'weak', amount: 1 },
    ],
  },
  m_whip: {
    id: 'm_whip',
    name: '채찍 일격',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'enemy',
    description: '5 데미지. 중독 +5.',
    effects: [
      { kind: 'damage', amount: 5 },
      { kind: 'apply_enemy', status: 'poison', amount: 5 },
    ],
  },
  m_showtime: {
    id: 'm_showtime',
    name: '무대 위로',
    type: 'skill',
    rarity: 'uncommon',
    cost: 0,
    target: 'self',
    description: 'HP -3. 에너지 +2.',
    effects: [
      { kind: 'lose_hp', amount: 3 },
      { kind: 'energy', amount: 2 },
    ],
  },
  m_rose_bind: {
    id: 'm_rose_bind',
    name: '장미 덩굴',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '방어도 +10. (이번 턴 한정)',
    effects: [{ kind: 'block', amount: 10 }],
    ethereal: true,
  },
  m_mirror: {
    id: 'm_mirror',
    name: '분신술',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '힘 +2.',
    effects: [{ kind: 'apply_self', status: 'strength', amount: 2 }],
  },
  m_goblin_charge: {
    id: 'm_goblin_charge',
    name: '소환: 돌격 정령',
    type: 'power',
    rarity: 'uncommon',
    cost: 1,
    target: 'self',
    description: '턴 종료 시 방어도 +3.',
    effects: [{ kind: 'apply_self', status: 'metallicize', amount: 3 }],
  },
  m_ouroboros: {
    id: 'm_ouroboros',
    name: '자기 재생',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'enemy',
    description: '12 데미지. 처치 시 영구 데미지 +4. 소멸.',
    effects: [{ kind: 'damage', amount: 12 }],
    exhaust: true,
    scaling: { kind: 'on_kill', amount: 4 },
  },
  m_doll_forest: {
    id: 'm_doll_forest',
    name: '인형의 숲',
    type: 'power',
    rarity: 'uncommon',
    cost: 2,
    target: 'self',
    description: '카드 소멸 시 에너지 +1.',
    effects: [{ kind: 'apply_self', status: 'on_exhaust_energy', amount: 1 }],
  },

  // ── Rare (1차 각성기) ──
  m_astral_storm: {
    id: 'm_astral_storm',
    name: '별빛 폭풍',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'enemy',
    description: '32 데미지.',
    effects: [{ kind: 'damage', amount: 32 }],
  },
  m_kasiyas: {
    id: 'm_kasiyas',
    name: '소환: 대정령',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'enemy',
    description: 'HP -5. 18 데미지. 유지. 소멸.',
    effects: [
      { kind: 'lose_hp', amount: 5 },
      { kind: 'damage', amount: 18 },
    ],
    retain: true,
    exhaust: true,
  },
  m_quasar: {
    id: 'm_quasar',
    name: '성간 폭발',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 21 데미지.',
    effects: [{ kind: 'damage_all', amount: 21 }],
  },
  m_fusion: {
    id: 'm_fusion',
    name: '원소 융합',
    type: 'power',
    rarity: 'rare',
    cost: 3,
    target: 'self',
    description: '턴 시작 시 힘 +2. 선천.',
    effects: [{ kind: 'apply_self', status: 'ritual', amount: 2 }],
    innate: true,
  },
  m_marionette: {
    id: 'm_marionette',
    name: '인형 조종',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'all_enemies',
    description: '모든 적에게 4 데미지.',
    effects: [{ kind: 'damage_all', amount: 4 }],
    exhaust: true,
  },

  // ── 마법사 콤보 시너지 ─────────────────────────────────────
  m_amplify: {
    id: 'm_amplify',
    name: '마력 증폭',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'enemy',
    description: '6 데미지. 직전이 방어카드면 +7 데미지.',
    effects: [
      { kind: 'damage', amount: 6 },
      { kind: 'conditional', condition: { kind: 'after_type', type: 'skill' }, then: [{ kind: 'damage', amount: 7 }] },
    ],
  },
  m_chain_lightning: {
    id: 'm_chain_lightning',
    name: '연쇄 번개',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'enemy',
    description: '4 데미지 3회. 이번 턴 2번째 이후 카드면 +1회 추가.',
    effects: [
      { kind: 'damage', amount: 4, times: 3 },
      { kind: 'conditional', condition: { kind: 'nth_or_more', n: 2 }, then: [{ kind: 'damage', amount: 4 }] },
    ],
  },
  m_arcane_burst: {
    id: 'm_arcane_burst',
    name: '비전 폭주',
    type: 'attack',
    rarity: 'rare',
    cost: 1,
    target: 'enemy',
    description: '데미지 = 4 × 이번 턴 사용한 카드 수. 소멸.',
    effects: [{ kind: 'damage_per_card_this_turn', amount: 4 }],
    exhaust: true,
  },

  // ── 풀 확장 (마법사) ──────────────────────────────────────
  m_frost_bolt: {
    id: 'm_frost_bolt',
    name: '냉기 화살',
    type: 'attack', rarity: 'common', cost: 1, target: 'enemy',
    description: '6 데미지. 빙결 +1.',
    effects: [
      { kind: 'damage', amount: 6 },
      { kind: 'apply_enemy', status: 'freeze', amount: 1 },
    ],
  },
  m_mana_charge: {
    id: 'm_mana_charge',
    name: '마나 충전',
    type: 'skill', rarity: 'uncommon', cost: 0, target: 'self',
    description: '에너지 +1. 1장 드로우. 소멸.',
    effects: [
      { kind: 'energy', amount: 1 },
      { kind: 'draw', amount: 1 },
    ],
    exhaust: true,
  },
  m_fire_burst: {
    id: 'm_fire_burst',
    name: '불꽃 폭발',
    type: 'attack', rarity: 'uncommon', cost: 2, target: 'all_enemies',
    description: '모든 적에게 9 데미지. 화상 +3.',
    effects: [
      { kind: 'damage_all', amount: 9 },
      { kind: 'apply_all', status: 'burn', amount: 3 },
    ],
  },
  m_energy_circuit: {
    id: 'm_energy_circuit',
    name: '에너지 회로',
    type: 'power', rarity: 'uncommon', cost: 1, target: 'self',
    description: '턴 종료 시 방어도 +4.',
    effects: [{ kind: 'apply_self', status: 'metallicize', amount: 4 }],
  },
  m_time_warp: {
    id: 'm_time_warp',
    name: '타임 워프',
    type: 'skill', rarity: 'rare', cost: 3, target: 'self',
    description: '카드 3장 드로우. 에너지 +2. 소멸.',
    effects: [
      { kind: 'draw', amount: 3 },
      { kind: 'energy', amount: 2 },
    ],
    exhaust: true,
  },
  m_arcane_orb: {
    id: 'm_arcane_orb',
    name: '비전 구체',
    type: 'attack', rarity: 'uncommon', cost: 1, target: 'enemy',
    description: '9 데미지. 직전이 방어카드면 +6 데미지.',
    effects: [
      { kind: 'damage', amount: 9 },
      { kind: 'conditional', condition: { kind: 'after_type', type: 'skill' }, then: [{ kind: 'damage', amount: 6 }] },
    ],
  },
};

const MAGICIAN_UPGRADE_MAP: Record<string, Partial<CardDef>> = {
  m_magic_missile:  { name: '마력 화살+',                description: '9 데미지.',                              effects: [{ kind: 'damage', amount: 9 }] },
  m_aura_shield:    { name: '마력 방벽+',                  description: '방어도 +8.',                             effects: [{ kind: 'block', amount: 8 }] },
  m_phase_shift:    { name: '차원 전환+',                   description: '10 데미지. 취약 +3.',                    effects: [{ kind: 'damage', amount: 10 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 3 }] },
  m_skystrike:      { name: '번개 일격+',                       description: '18 데미지.',                             effects: [{ kind: 'damage', amount: 18 }] },
  m_dragon_tooth:   { name: '용의 이빨+',                       description: '7 데미지를 두 번.',                      effects: [{ kind: 'damage', amount: 7, times: 2 }] },
  m_lantern:        { name: '화염 등불+',                description: '8 데미지. 화상 +5.',                     effects: [{ kind: 'damage', amount: 8 }, { kind: 'apply_enemy', status: 'burn', amount: 5 }] },
  m_air_lantern:    { name: '공중 화염+',           description: '모든 적에게 11 데미지.',                 effects: [{ kind: 'damage_all', amount: 11 }] },
  m_petal:          { name: '꽃잎 폭발+',                     description: '모든 적에게 7 데미지. 취약 +1.',         effects: [{ kind: 'damage_all', amount: 7 }, { kind: 'apply_all', status: 'vulnerable', amount: 1 }] },
  m_pluto:          { name: '명왕성의 힘+',                     description: '7 데미지. 방어도 +7.',                   effects: [{ kind: 'damage', amount: 7 }, { kind: 'block', amount: 7 }] },
  m_frost:          { name: '서리 머리+',              description: '7 데미지. 빙결 +2. 소멸.',               effects: [{ kind: 'damage', amount: 7 }, { kind: 'apply_enemy', status: 'freeze', amount: 2 }] },
  m_disenchant:     { name: '마력 해제+',                 description: '힘 +4.',                                 effects: [{ kind: 'apply_self', status: 'strength', amount: 4 }] },
  m_no_entry:       { name: '접근 금지!+',                 description: '방어도 +9. 무작위 카드 1장 소멸.',       effects: [{ kind: 'block', amount: 9 }, { kind: 'exhaust_random_hand' }] },
  m_summon_horus:   { name: '소환 : 기갑 골렘+',     description: '2장 드로우. 무작위 카드 1장 소멸.',      effects: [{ kind: 'draw', amount: 2 }, { kind: 'exhaust_random_hand' }] },
  m_blossom:        { name: '가시 회전+',              description: '15 데미지. 취약 +2. 약화 +2.',           effects: [{ kind: 'damage', amount: 15 }, { kind: 'apply_enemy', status: 'vulnerable', amount: 2 }, { kind: 'apply_enemy', status: 'weak', amount: 2 }] },
  m_whip:           { name: '채찍 일격+',                     description: '7 데미지. 중독 +7.',                     effects: [{ kind: 'damage', amount: 7 }, { kind: 'apply_enemy', status: 'poison', amount: 7 }] },
  m_showtime:       { name: '무대 위로+',                     description: 'HP -2. 에너지 +3.',                      effects: [{ kind: 'lose_hp', amount: 2 }, { kind: 'energy', amount: 3 }] },
  m_rose_bind:      { name: '장미 덩굴+',                  description: '방어도 +13.',                            effects: [{ kind: 'block', amount: 13 }] },
  m_mirror:         { name: '분신술+',                 description: '힘 +3.',                                 effects: [{ kind: 'apply_self', status: 'strength', amount: 3 }] },
  m_goblin_charge:  { name: '소환: 돌격 정령+',   description: '턴 종료 시 방어도 +4.',                  effects: [{ kind: 'apply_self', status: 'metallicize', amount: 4 }] },
  m_ouroboros:      { name: '자기 재생+',                description: '15 데미지. 처치 시 영구 데미지 +6. 소멸.', effects: [{ kind: 'damage', amount: 15 }] },
  m_doll_forest:    { name: '인형의 숲+',                 description: '카드 소멸 시 에너지 +1, 카드 1장 드로우.', effects: [{ kind: 'apply_self', status: 'on_exhaust_energy', amount: 1 }, { kind: 'apply_self', status: 'on_exhaust_draw', amount: 1 }] },
  m_astral_storm:   { name: '별빛 폭풍+',              description: '42 데미지.',                             effects: [{ kind: 'damage', amount: 42 }] },
  m_kasiyas:        { name: '소환: 대정령+',            description: 'HP -3. 24 데미지. 유지. 소멸.',          effects: [{ kind: 'lose_hp', amount: 3 }, { kind: 'damage', amount: 24 }] },
  // 콤보 시너지
  m_amplify:        { name: '마력 증폭+',  description: '9 데미지. 직전이 방어카드면 +10 데미지.',
                       effects: [{ kind: 'damage', amount: 9 }, { kind: 'conditional', condition: { kind: 'after_type', type: 'skill' }, then: [{ kind: 'damage', amount: 10 }] }] },
  m_chain_lightning:{ name: '연쇄 번개+',  description: '5 데미지 3회. 이번 턴 2번째 이후 카드면 +2회 추가.',
                       effects: [{ kind: 'damage', amount: 5, times: 3 }, { kind: 'conditional', condition: { kind: 'nth_or_more', n: 2 }, then: [{ kind: 'damage', amount: 5, times: 2 }] }] },
  m_arcane_burst:   { name: '비전 폭주+',  description: '데미지 = 5 × 이번 턴 사용한 카드 수. 소멸.',
                       effects: [{ kind: 'damage_per_card_this_turn', amount: 5 }] },
  m_quasar:         { name: '성간 폭발+',          description: '모든 적에게 28 데미지.',                 effects: [{ kind: 'damage_all', amount: 28 }] },
  m_fusion:         { name: '원소 융합+',              description: '턴 시작 시 힘 +3. 선천.',                effects: [{ kind: 'apply_self', status: 'ritual', amount: 3 }] },
  m_marionette:     { name: '인형 조종+',                 description: '모든 적에게 6 데미지.',                  effects: [{ kind: 'damage_all', amount: 6 }] },
  // 풀 확장
  m_frost_bolt:     { name: '냉기 화살+',   description: '8 데미지. 빙결 +2.',                     effects: [{ kind: 'damage', amount: 8 }, { kind: 'apply_enemy', status: 'freeze', amount: 2 }] },
  m_mana_charge:    { name: '마나 충전+',   description: '에너지 +2. 2장 드로우. 소멸.',           effects: [{ kind: 'energy', amount: 2 }, { kind: 'draw', amount: 2 }] },
  m_fire_burst:     { name: '불꽃 폭발+',   description: '모든 적에게 12 데미지. 화상 +4.',         effects: [{ kind: 'damage_all', amount: 12 }, { kind: 'apply_all', status: 'burn', amount: 4 }] },
  m_energy_circuit: { name: '에너지 회로+', description: '턴 종료 시 방어도 +6.',                   effects: [{ kind: 'apply_self', status: 'metallicize', amount: 6 }] },
  m_time_warp:      { name: '타임 워프+',   description: '카드 5장 드로우. 에너지 +3. 소멸.',       effects: [{ kind: 'draw', amount: 5 }, { kind: 'energy', amount: 3 }] },
  m_arcane_orb:     { name: '비전 구체+',   description: '12 데미지. 직전이 방어카드면 +8 데미지.',
                      effects: [{ kind: 'damage', amount: 12 }, { kind: 'conditional', condition: { kind: 'after_type', type: 'skill' }, then: [{ kind: 'damage', amount: 8 }] }] },
};

export function magicianGetEffectiveDef(card: CardInstance): CardDef {
  const base = MAGICIAN_CARD_DEFS[card.defId];
  if (!card.upgraded) return base;
  const up = MAGICIAN_UPGRADE_MAP[card.defId];
  return up ? { ...base, ...up } : base;
}

export function canUpgradeMagician(card: CardInstance): boolean {
  return (card.upgraded ?? 0) < 2 && card.defId in MAGICIAN_UPGRADE_MAP;
}

const MAGICIAN_CARD_LIST = Object.values(MAGICIAN_CARD_DEFS);
export const MAGICIAN_COMMON_CARDS   = MAGICIAN_CARD_LIST.filter((c) => c.rarity === 'common');
export const MAGICIAN_UNCOMMON_CARDS = MAGICIAN_CARD_LIST.filter((c) => c.rarity === 'uncommon');
export const MAGICIAN_RARE_CARDS     = MAGICIAN_CARD_LIST.filter((c) => c.rarity === 'rare');
